name: hola-mundo-test
run-name: !Estoy probando mi primer workflow en GitHub Actions
on: [push]
jobs:
  hola-mundo-compile:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Definir una variable de entorno
      run: echo "HOLA_MUNDO=Hola Mundo" >> $GITHUB_ENV
    - name: Run hola-mundo
      run: php index.php
