name: hola-mundo-trigger

on:
  push:
    branches:
      - 'feature_test/*'
    paths:
      - '**/*.js'

  pull_request:
    types:
      - opened
      - labeled
    branches:
      - 'main'
    paths:
      - '**/*.js'

  schedule:
    - cron: '15 22 * * *'
jobs:
  hola-mundo-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repo en el Runner
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node index.js

      - name: Expresión con funciones
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Evento: ${{ github.event_name }}"